version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data   
  redisinsight:
    image: redis/redisinsight:latest
    ports:
        - "8001:5540" 
    depends_on: 
        - redis
    volumes:
        - redis-insight:/data
  

volumes:
  redis-data:
  redis-insight:
